[package]
name = "mundis-replica-lib"
version = "0.9.26"
authors = ["Mundis Maintainers <maintainers@mundis.io>"]
edition = "2021"
repository = "https://github.com/mundisnetwork/axis"
license = "Apache-2.0"
homepage = "https://mundis.io/"

[dependencies]
crossbeam-channel = "0.5"
futures-util = "0.3"
log = "0.4.11"
prost = "0.10.0"
mundis-rpc = { path = "../rpc", version = "=0.9.26" }
mundis-runtime = { path = "../runtime", version = "=0.9.26" }
mundis-sdk = { path = "../sdk", version = "=0.9.26" }
tokio = { version = "~1.14.1", features = ["full"] }
tonic = { version = "0.7.1", features = ["tls", "transport"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
tonic-build = "0.7.0"
