[package]
authors = ["Mundis Maintainers <maintainers@mundis.io>"]
edition = "2021"
homepage = "https://mundis.io/"
license = "Apache-2.0"
name = "proto"
publish = false
repository = "https://github.com/mundisnetwork/axis"
version = "0.9.22"

[workspace]

[dependencies]
tonic-build = "0.7.0"
