[package]
name = "mundis-version"
version = "1.9.19"
authors = ["Mundis Maintainers <maintainers@mundis.io>"]
repository = "https://github.com/mundisnetwork/axis"
license = "Apache-2.0"
homepage = "https://mundis.io/"
edition = "2021"

[dependencies]
log = "0.4.14"
serde = "1.0.130"
serde_derive = "1.0.103"
mundis-frozen-abi = { path = "../frozen-abi", version = "=1.9.19" }
mundis-frozen-abi-macro = { path = "../frozen-abi/macro", version = "=1.9.19" }
mundis-sdk = { path = "../sdk", version = "=1.9.19" }

[lib]
name = "mundis_version"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
rustc_version = "0.4"
