[package]
name = "mundis-program"
version = "0.9.29"
authors = ["Mundis Maintainers <maintainers@mundis.io>"]
repository = "https://github.com/mundisnetwork/axis"
homepage = "https://mundis.io/"
readme = "README.md"
license = "Apache-2.0"
edition = "2021"

[dependencies]
bincode = "1.3.1"
blake3 = { version = "1.2.0", features = ["traits-preview"] }
borsh = "0.9.1"
borsh-derive = "0.9.1"
bs58 = "0.4.0"
bytemuck = { version = "1.7.2", features = ["derive"] }
bv = { version = "0.11.1", features = ["serde"] }
itertools =  "0.10.1"
lazy_static = "1.4.0"
log = "0.4.14"
num-derive = "0.3"
num-traits = "0.2"
rustversion = "1.0.3"
serde = "1.0.112"
serde_bytes = "0.11"
serde_derive = "1.0.103"
sha2 = "0.9.2"
sha3 = "0.9.1"
mundis-frozen-abi = { path = "../../frozen-abi", version = "=0.9.29" }
mundis-frozen-abi-macro = { path = "../../frozen-abi/macro", version = "=0.9.29" }
mundis-sdk-macro = { path = "../macro", version = "=0.9.29" }
thiserror = "1.0"

[target.'cfg(not(target_arch = "bpf"))'.dependencies]
bitflags = "1.3.1"
base64 = "0.13"
curve25519-dalek = "3.0.0"
libsecp256k1 = "0.6.0"
rand = "0.7.0"
mundis-logger = { path = "../../logger", version = "=0.9.29" }
itertools = "0.10.1"
wasm-bindgen = "0.2"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
console_log = "0.2.0"
js-sys = "0.3.55"
getrandom = { version = "0.1", features = ["wasm-bindgen"] }

[target.'cfg(not(target_pointer_width = "64"))'.dependencies]
parking_lot = "0.11"

[dev-dependencies]
anyhow = "1.0.45"
assert_matches = "1.3.0"
bincode = "1.3.1"
borsh = "0.9.1"
borsh-derive = "0.9.1"
serde_json = "1.0.56"
static_assertions = "1.1.0"

[build-dependencies]
rustc_version = "0.4"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = ["cdylib", "rlib"]
