[package]
name = "mundis-rpc"
version = "0.9.24"
authors = ["Mundis Maintainers <maintainers@mundis.io>"]
repository = "https://github.com/mundisnetwork/axis"
license = "Apache-2.0"
homepage = "https://mundis.io/"
edition = "2021"

[dependencies]
base64 = "0.12.3"
bincode = "1.3.3"
bs58 = "0.4.0"
crossbeam-channel = "0.5"
dashmap = "4.0.2"
itertools = "0.10.1"
jsonrpc-core = "18.0.0"
jsonrpc-core-client = { version = "18.0.0", features = ["ipc", "ws"] }
jsonrpc-derive = "18.0.0"
jsonrpc-http-server = "18.0.0"
jsonrpc-pubsub = "18.0.0"
jsonrpc-ws-server = "18.0.0"
libc = "0.2.108"
log = "0.4.14"
rayon = "1.5.1"
regex = "1.5.4"
serde = "1.0.130"
serde_derive = "1.0.103"
serde_json = "1.0.72"
soketto = "0.7"
mundis-account-decoder = { path = "../account-decoder", version = "=0.9.24" }
mundis-client = { path = "../client", version = "=0.9.24" }
mundis-entry = { path = "../entry", version = "=0.9.24" }
mundis-faucet = { path = "../faucet", version = "=0.9.24" }
mundis-gossip = { path = "../gossip", version = "=0.9.24" }
mundis-ledger = { path = "../ledger", version = "=0.9.24" }
mundis-measure = { path = "../measure", version = "=0.9.24" }
mundis-metrics = { path = "../metrics", version = "=0.9.24" }
mundis-perf = { path = "../perf", version = "=0.9.24" }
mundis-poh = { path = "../poh", version = "=0.9.24" }
mundis-rayon-threadlimit = { path = "../rayon-threadlimit", version = "=0.9.24" }
mundis-runtime = { path = "../runtime", version = "=0.9.24" }
mundis-sdk = { path = "../sdk", version = "=0.9.24" }
mundis-send-transaction-service = { path = "../send-transaction-service", version = "=0.9.24" }
mundis-streamer = { path = "../streamer", version = "=0.9.24" }
mundis-storage-bigtable = { path = "../storage-bigtable", version = "=0.9.24" }
mundis-transaction-status = { path = "../transaction-status", version = "=0.9.24" }
mundis-version = { path = "../version", version = "=0.9.24" }
mundis-vote-program = { path = "../programs/vote", version = "=0.9.24" }
mundis-token-program = { path = "../programs/token", version = "=0.9.24" }
stream-cancel = "0.8.1"
thiserror = "1.0"
tokio = { version = "~1.14.1", features = ["full"] }
tokio-util = { version = "0.6", features = ["codec", "compat"] }

[dev-dependencies]
serial_test = "0.5.1"
mundis-net-utils = { path = "../net-utils", version = "=0.9.24" }
mundis-stake-program = { path = "../programs/stake", version = "=0.9.24" }
symlink = "0.1.0"

[lib]
crate-type = ["lib"]
name = "mundis_rpc"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
