[package]
name = "mundis-validator"
version = "0.9.25"
authors = ["Mundis Maintainers <maintainers@mundis.io>"]
edition = "2021"
repository = "https://github.com/mundisnetwork/axis"
license = "Apache-2.0"
homepage = "https://mundis.io/"
default-run = "mundis-validator"

[dependencies]
chrono = { version = "0.4.11", features = ["serde"] }
clap = "2.33.1"
console = "0.15.0"
core_affinity = "0.5.10"
fd-lock = "3.0.1"
indicatif = "0.16.2"
jsonrpc-core = "18.0.0"
jsonrpc-core-client = { version = "18.0.0", features = ["ipc", "ws"] }
jsonrpc-derive = "18.0.0"
jsonrpc-ipc-server = "18.0.0"
jsonrpc-server-utils= "18.0.0"
log = "0.4.14"
num_cpus = "1.13.0"
rand = "0.7.0"
mundis-clap-utils = { path = "../clap-utils", version = "=0.9.25" }
mundis-cli-config = { path = "../cli-config", version = "=0.9.25" }
mundis-client = { path = "../client", version = "=0.9.25" }
mundis-core = { path = "../core", version = "=0.9.25" }
mundis-download-utils = { path = "../download-utils", version = "=0.9.25" }
mundis-entry = { path = "../entry", version = "=0.9.25" }
mundis-faucet = { path = "../faucet", version = "=0.9.25" }
mundis-gossip = { path = "../gossip", version = "=0.9.25" }
mundis-ledger = { path = "../ledger", version = "=0.9.25" }
mundis-logger = { path = "../logger", version = "=0.9.25" }
mundis-metrics = { path = "../metrics", version = "=0.9.25" }
mundis-net-utils = { path = "../net-utils", version = "=0.9.25" }
mundis-perf = { path = "../perf", version = "=0.9.25" }
mundis-poh = { path = "../poh", version = "=0.9.25" }
mundis-replica-lib = { path = "../replica-lib", version = "=0.9.25" }
mundis-rpc = { path = "../rpc", version = "=0.9.25" }
mundis-runtime = { path = "../runtime", version = "=0.9.25" }
mundis-sdk = { path = "../sdk", version = "=0.9.25" }
mundis-send-transaction-service = { path = "../send-transaction-service", version = "=0.9.25" }
mundis-streamer = { path = "../streamer", version = "=0.9.25" }
mundis-test-validator = { path = "../test-validator", version = "=0.9.25" }
mundis-version = { path = "../version", version = "=0.9.25" }
mundis-vote-program = { path = "../programs/vote", version = "=0.9.25" }
symlink = "0.1.0"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = {package = "tikv-jemallocator", version = "0.4.1", features = ["unprefixed_malloc_on_supported_platforms"]}

[target."cfg(unix)".dependencies]
libc = "0.2.108"
signal-hook = "0.3.10"
sysctl = "0.4.3"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
