[package]
name = "mundis-runtime"
version = "1.9.18"
authors = ["Mundis Maintainers <maintainers@mundis.io>"]
repository = "https://github.com/mundisnetwork/axis"
license = "Apache-2.0"
homepage = "https://mundis.io/"
edition = "2021"

[dependencies]
arrayref = "0.3.6"
bincode = "1.3.3"
blake3 = "1.2.0"
bv = { version = "0.11.1", features = ["serde"] }
bytemuck = "1.7.2"
byteorder = "1.4.3"
bzip2 = "0.4.3"
dashmap = { version = "4.0.2", features = ["rayon", "raw-api"] }
crossbeam-channel = "0.5"
dir-diff = "0.3.2"
flate2 = "1.0.22"
fnv = "1.0.7"
index_list = "0.2.7"
itertools = "0.10.1"
lazy_static = "1.4.0"
log = "0.4.14"
memmap2 = "0.5.0"
num_cpus = "1.13.0"
num-derive = { version = "0.3" }
num-traits = { version = "0.2" }
ouroboros = "0.13.0"
rand = "0.7.0"
rayon = "1.5.1"
regex = "1.5.4"
serde = { version = "1.0.130", features = ["rc"] }
serde_derive = "1.0.103"
mundis-address-lookup-table-program = { path = "../programs/address-lookup-table", version = "=1.9.18" }
mundis-bloom = { path = "../bloom", version = "=1.9.18" }
mundis-config-program = { path = "../programs/config", version = "=1.9.18" }
mundis-compute-budget-program = { path = "../programs/compute-budget", version = "=1.9.18" }
mundis-frozen-abi = { path = "../frozen-abi", version = "=1.9.18" }
mundis-frozen-abi-macro = { path = "../frozen-abi/macro", version = "=1.9.18" }
mundis-logger = { path = "../logger", version = "=1.9.18" }
mundis-measure = { path = "../measure", version = "=1.9.18" }
mundis-metrics = { path = "../metrics", version = "=1.9.18" }
mundis-program-runtime = { path = "../program-runtime", version = "=1.9.18" }
mundis-rayon-threadlimit = { path = "../rayon-threadlimit", version = "=1.9.18" }
mundis-sdk = { path = "../sdk", version = "=1.9.18" }
mundis-stake-program = { path = "../programs/stake", version = "=1.9.18" }
mundis-vote-program = { path = "../programs/vote", version = "=1.9.18" }
mundis-memo-program = { path = "../programs/memo", version = "=1.9.18" }
mundis-token-program = { path = "../programs/token", version = "=1.9.18" }
mundis-token-account-program = { path = "../programs/token-account", version = "=1.9.18" }
symlink = "0.1.0"
tar = "0.4.37"
fs_extra = "1.2.0"
tempfile = "3.2.0"
thiserror = "1.0"
zstd = "0.9.0"

[lib]
crate-type = ["lib"]
name = "mundis_runtime"

[dev-dependencies]
assert_matches = "1.5.0"
ed25519-dalek = "=1.0.1"
libsecp256k1 = "0.6.0"
rand_chacha = "0.2.2"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
rustc_version = "0.4"
