#!/bin/sh

/usr/local/bin/mundis-keygen new --no-bip39-passphrase -f -o /var/lib/mundis/validator-vote-account.json
/usr/local/bin/mundis-keygen new --no-bip39-passphrase -f -o /var/lib/mundis/validator-identity.json

chown -R mundis:mundis /var/log/mundis /var/lib/mundis /mnt/ledger /mnt/accounts

sysctl --system

systemctl daemon-reload
systemctl restart logrotate.service
systemctl disable mundis-validator
