[package]
name = "mundis-storage-bigtable"
version = "0.9.29"
authors = ["Mundis Maintainers <maintainers@mundis.io>"]
repository = "https://github.com/mundisnetwork/axis"
license = "Apache-2.0"
homepage = "https://mundis.io/"
edition = "2021"

[dependencies]
backoff = { version = "0.3.0", features = ["tokio"] }
bincode = "1.3.3"
bzip2 = "0.4.3"
enum-iterator = "0.7.0"
flate2 = "1.0.22"
goauth = "0.10.0"
log = "0.4.14"
prost = "0.10.0"
prost-types = "0.10.0"
serde = "1.0.130"
serde_derive = "1.0.103"
smpl_jwt = "0.6.1"
mundis-metrics = { path = "../metrics", version = "=0.9.29" }
mundis-sdk = { path = "../sdk", version = "=0.9.29" }
mundis-storage-proto = { path = "../storage-proto", version = "=0.9.29" }
mundis-transaction-status = { path = "../transaction-status", version = "=0.9.29" }
thiserror = "1.0"
tonic = { version = "0.7.1", features = ["tls", "transport"] }
zstd = "0.9.0"

# openssl is a dependency of the goauth and smpl_jwt crates, but explicitly
# declare it here as well to activate the "vendored" feature that builds OpenSSL
# statically...
[target."cfg(not(windows))".dependencies]
openssl = { version = "0.10", features = ["vendored"] }
# ...except on Windows to avoid having to deal with getting CI past a build-time
# Perl dependency
[target."cfg(windows)".dependencies]
openssl = { version = "0.10", features = [] }

[lib]
crate-type = ["lib"]
name = "mundis_storage_bigtable"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
