[package]
name = "mundis-sdk"
version = "0.9.21"
authors = ["Mundis Maintainers <maintainers@mundis.io>"]
repository = "https://github.com/mundisnetwork/axis"
homepage = "https://mundis.io/"
license = "Apache-2.0"
edition = "2021"

[features]
default = [
  "full" # functionality that is not compatible or needed for on-chain programs
]
full = [
    "assert_matches",
    "byteorder",
    "chrono",
    "generic-array",
    "memmap2",
    "rand",
    "rand_chacha",
    "serde_json",
    "ed25519-dalek",
    "ed25519-dalek-bip32",
    "mundis-logger",
    "libsecp256k1",
    "sha3",
    "digest",
]

[dependencies]
assert_matches = { version = "1.5.0", optional = true }
bincode = "1.3.3"
bitflags = "1.3.1"
bytemuck = { version = "1.7.2", features = ["derive"] }
borsh = "0.9.0"
base64 = "0.13"
bs58 = "0.4.0"
byteorder = { version = "1.4.3", optional = true }
chrono = { default-features = false, features = ["alloc"], version = "0.4", optional = true }
curve25519-dalek = { version = "3.2.0", optional = true }
derivation-path = { version = "0.1.3", default-features = false }
digest = { version = "0.9.0", optional = true }
ed25519-dalek = { version = "=1.0.1", optional = true }
ed25519-dalek-bip32 = { version = "0.1.1", optional = true }
generic-array = { version = "0.14.4", default-features = false, features = ["serde", "more_lengths"], optional = true }
hmac = "0.11.0"
itertools =  "0.10.1"
lazy_static = "1.4.0"
libsecp256k1 = { version = "0.6.0", optional = true }
log = "0.4.14"
memmap2 = { version = "0.5.0", optional = true }
num-derive = "0.3"
num-traits = "0.2"
pbkdf2 = { version = "0.9.0", default-features = false }
qstring = "0.7.2"
rand = { version = "0.7.0", optional = true }
rand_chacha = { version = "0.2.2", optional = true }
rustversion = "1.0.5"
serde = "1.0.130"
serde_bytes = "0.11"
serde_derive = "1.0.103"
serde_json = { version = "1.0.72", optional = true }
sha2 = "0.9.8"
sha3 = { version = "0.9.1", optional = true }
mundis-logger = { path = "../logger", version = "=0.9.21", optional = true }
mundis-frozen-abi = { path = "../frozen-abi", version = "=0.9.21" }
mundis-frozen-abi-macro = { path = "../frozen-abi/macro", version = "=0.9.21" }
mundis-program = { path = "program", version = "=0.9.21" }
mundis-sdk-macro = { path = "macro", version = "=0.9.21" }
thiserror = "1.0"
uriparse = "0.6.3"
wasm-bindgen = "0.2"
num-format = "0.4.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3.55"

[dev-dependencies]
anyhow = "1.0.45"
curve25519-dalek = "3.2.0"
tiny-bip39 = "0.8.2"

[build-dependencies]
rustc_version = "0.4"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = ["cdylib", "rlib"]
