#!/usr/bin/env bash

here=$(dirname "$0")
there="$here/.."

maybe_bpf_sdk="--bpf-sdk $there/sdk/bpf"
for a in "$@"; do
  if [[ $a = --bpf-sdk ]]; then
    maybe_bpf_sdk=
  fi
done

export CARGO_BUILD_BPF="$here"/cargo-build-bpf
set -x
exec "$there"/cargo run --manifest-path "$there"/sdk/cargo-test-bpf/Cargo.toml -- $maybe_bpf_sdk "$@"
