name: Rust

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --verbose
